name: whatif
description: A party guessing game
version: 0.2.2
homepage: https://github.com/jmminch/whatif

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.1
  shelf_static: ^1.1.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
